# Generated by Django 5.2.7 on 2025-10-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='method',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='deposit',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='withdrawal_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
