# Generated by Django 5.2.7 on 2025-11-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_deposit_method_deposit_proof_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='reference',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='reference',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
